MERGE INTO product (name, price, calories, category) VALUES ('Persistent', 6.43, 1845, 'beer');
MERGE INTO product (name, price, calories, category) VALUES ('knowledge base', 11.68, 1501, 'tea');
MERGE INTO product (name, price, calories, category) VALUES ('contingency', 6.83, 521, 'beer');
MERGE INTO product (name, price, calories, category) VALUES ('Diverse', 11.7, 760, 'hot coco');
MERGE INTO product (name, price, calories, category) VALUES ('Intuitive', 6.45, 1921, 'beer');
MERGE INTO product (name, price, calories, category) VALUES ('database', 12.77, 426, 'hot coco');
MERGE INTO product (name, price, calories, category) VALUES ('Enhanced', 8.42, 228, 'hot coco');
MERGE INTO product (name, price, calories, category) VALUES ('infrastructure', 12.98, 1290, 'coffee');
MERGE INTO product (name, price, calories, category) VALUES ('installation', 5.18, 1982, 'hot coco');
MERGE INTO product (name, price, calories, category) VALUES ('Exclusive', 4.76, 1183, 'cocktail');
MERGE INTO product (name, price, calories, category) VALUES ('Virtual', 14.95, 1210, 'coffee');
MERGE INTO product (name, price, calories, category) VALUES ('emulation', 3.29, 909, 'hot coco');
MERGE INTO product (name, price, calories, category) VALUES ('static', 11.23, 311, 'cocktail');
MERGE INTO product (name, price, calories, category) VALUES ('concept', 9.32, 543, 'beer');
MERGE INTO product (name, price, calories, category) VALUES ('Mandatory', 12.6, 1057, 'coffee');
MERGE INTO product (name, price, calories, category) VALUES ('intangible', 7.57, 987, 'cocktail');
MERGE INTO product (name, price, calories, category) VALUES ('User-friendly', 10.33, 1403, 'tea');
MERGE INTO product (name, price, calories, category) VALUES ('process improvement', 3.08, 566, 'cocktail');
MERGE INTO product (name, price, calories, category) VALUES ('Open-source', 9.78, 1248, 'cocktail');
MERGE INTO product (name, price, calories, category) VALUES ('Sharable', 4.72, 492, 'tea');